db/teams.json

Update social networks from every team

---

db/leaderboard.json

Arregle los links de las redes sociales de los equipos en el archivo `leaderboard.json`.

Fix teams social networks

---

db/leaderboard.json

Add the channels

---

api/index.js

Actualizando código teniendo en cuenta el problema de la configuración del formateador.
Disculpas por el error!!!

correct code of api route of team info per id

---

api/index.test.js
package.json

* install `vitest`
* add test script
* fix initial test

build: setup vitest

---

db/teams.json

El Canal oficial es el [twitch de Irker Casillas](https://www.twitch.tv/ikercasillas)

Fix oficial channel 1K FC team

---

src/layouts/Layout.astro
src/pages/index.astro

Change the language at Layout.astro

Change language

---

jsconfig.json
src/layouts/Layout.astro
src/pages/index.astro
src/pages/team/[teamId].astro

Frontend Astro improvements

---

db/leaderboard.json
scraping/leaderboard.js

Hello midu, just saw that we are mispelling "losses" throughout the project, [see correct "losses" spelling](https://www.premierleague.com/stats/top/clubs/losses?co=1&se=-1&co=-1?se=-1). Hope this helps :) thanks for sharing your knowledge and for your amazing work!!!

fixed losses spelling throughout the project

---

db/mvpList.json
scraping/leaderboard.js
scraping/mvp.js
scraping/utils.js

This PR includes scrping for MVP. output is stored in a JSON containing the following info
```
[
{
"rank": 1,
"playerName": "Feliu",
"gamesPlayed": 1,
"mvps": 1,
"team": "Saiyans FC",
"image": "https://kings-league-api.midudev.workers.dev/static/logos/saiyans-fc.svg"
},
...
]
```
also **URLS** data and **scrape** function were moved to **utils.js** file to be shared between other scraping instances

Mvp scraping

---

CONTRIBUTING.md

I've just added some content in CONTRIBUTING.md file, outlining some guidelines for those of you who want to contribute to the project. This is just a first draft, so if you have any suggestions for improvements or additional information that should be included, do it please!

Add: version 1 contributing file

---

api/index.js
db/assists.json
db/index.js
scraping/assists.js
scraping/mvp.js
scraping/top_scorer.js
scraping/utils.js

Adding assists scraping from kingsleeague site.

feat: Adding assists scraping

---

api/index.js
scraping/coaches.js

I changed the "coachs" word because it should be "coaches".

Typo: changing "coachs" for "coaches"

---

.github/workflows/checks.yml
.github/workflows/deploy-api.yml

This should be merged once the problem with the tests is solved, just to prevent them from failing.

execute tests in push and PR's

---

package.json

Add husky and seeting for run eslint and prettier in push.
Also run test in each commit and push.
🐶

Add: husky and settings

---

api/index.test.js

Test: Add test for /presidents route

---

src/components/Header.astro

I changed the header to add six logos, the kings league logo and six more logos. Also, the menu is centered.

Center logos in header

---

.github/workflows/checks.yml
.github/workflows/deploy-api.yml

* hay algunas actions que no han terminado de ejecutarse por alguna razón, por eso añado este timeout

add timeout for prevent eternal action run

---

api/index.js

Añado dos rutas para obtener con mayor facilidad la información de un jugador destacado por el ranking que tenga.
`GET` `/top-scorer/:rank` : Devuelve un goleador por el ranking que tenga
`GET` `/top-assists/:rank` : Devuelve un asistidor por el ranking que tenga

add routes of tops scorrer and assits per ranking

---

src/pages/team/[teamId].astro

list of players

---

package.json

added official vitest package for testing ui

add package vitest ui

---

api/index.js
db/coaches.json

Añado la ruta de `GET coaches/:teamId`, la cual obtiene un entrenador basado en el id del equipo.

add route that get coach per team id

---

README.md
api/index.js

Actualizo la información del README.md y en la respuesta de la ruta inicial de la api con la información de las nuevas rutas.

update info of new routes in readme.md and root route

---

src/components/Unete.astro
src/pages/index.astro

Unete Button Component

---

src/pages/reglamento/index.astro

new style to the regulation page

add: regulation page styles

---

src/components/Footer.astro

Adding social media links in the Footer component

feat: add social media links

---

src/pages/calendario/index.astro
src/pages/contacto/index.astro
src/pages/estadisticas/index.astro

Añado el layout principal a las rutas que estaban vacias.

add initial layout at routes that is empty

---

src/components/Container.astro
src/components/Footer.astro

Improve responsive for the footer component
- View for 1024
- View for 768
- View for 640
- View for 375

Style: Improve responsive in the footer component

---

src/components/Unete.astro

Use new style "font-title" and use uppercase
Minor fix: chage double quoted import to single quoted

fix-style: change font-black to font-title

---

src/components/Sponsors.astro

Style: add gradient and border to Sponsors

---

src/components/Footer.astro

fix-style: Aligned footer first nav with second nav

---

CONTRIBUTING.md

Improve consistency.
- Beautify Midudev's article link
- Update title.
- Add a period at the end of every list item.
- Fix "Introduction" title to render correctly.
- Add a sub-list in the "semantic commits" section.

docs: improve consistency

---

src/components/Footer.astro

Se cambiaron el span de las pagina del footer por <a> con su respectiva redireccion,

Urls del footer

---

src/components/ScheduleRow.astro
src/pages/calendario/index.astro
src/services/schedule.js

Initial styles for the `/calendario` page:

Feat: Schedule page content and initial styles

---

db/schedule.json
scraping/schedule.js

Teams shortname to make it easy the responsive view.

Feat: Add teams shortname on schedule scraper

---

scraping/top_5_statistics.js

(incomplete)
search image in players_twelve

create function top 5

---

src/components/ScheduleRow.astro

Add hover effects and different styles for the score on played games.
Hover:

Improve schedule table styles

---

db/schedule.json
scraping/schedule.js

Add the match hour or null if it's not defined.

Feat: Include the match hour on Schedule scraper

---

src/components/ScheduleRow.astro
src/pages/calendario/index.astro

New styles calender page

---

src/components/Footer.astro
src/pages/estadisticas/clasificacion/index.astro
src/pages/estadisticas/index.astro

Tiny fix that adds a "tilde" to "Estadísticas" across pages.

Fix: Add tilde to word

---

src/components/ScheduleRow.astro

Added links to teams at calendar.

Add links to teams at scheduler

---

src/components/TeamPagePlayers.astro
src/pages/team/[teamId].astro

Edited some styling in the teams page so it looks OK on mobile.

fix: edited styling for teams page

---

src/components/Header.astro
src/components/NextMatchesTable.astro
src/components/ScheduleRow.astro
src/pages/index.astro

Before / After
<div style='display: flex'>
</div>
https://user-images.githubusercontent.com/16955362/211190278-4f9f3c8b-4deb-4b75-bc69-f94b618cb025.mp4

fix layout home mobile

---

src/pages/contacto/index.astro

- Improving font sizes consistency
- Adding Google Maps Iframe
- Making layout responsive
<div width="300">
</div>

feat: beautify contact page

---

db/index.test.js

Image URL was changed by Midu.

Fix: 🧪 Team image test

---

api/index.test.js
db/index.test.js

Test expected properties and properties types. 
Created from #209.

Test: `/players-12` endpoint

---

api/index.js

Just a formated code, converting an arrow function with return in an implicit return for simple statements.

one line return

---

src/components/Footer.astro
src/components/NextMatchesTable.astro
src/components/PlayerPrizeCard.astro
src/components/SocialNetworks.astro
src/components/TeamPagePlayers.astro
src/components/TeamsSelectorCards.astro
src/pages/team/[teamId].astro

Fix issues reported by lighthouse on home page.

fix issues reported by lighthouse

---

api/index.test.js
db/index.test.js

Test properties and properties types on `/top-scorers`, `/top-assists` and `/mvp` routes. 
Also create the `checkProperties` function to avoid repeating code (**didn't touch / refactor existing test**)
Created from #209.

Test: (Some) Statistics endpoints

---

src/components/Header.astro
src/components/TeamsSelectorCards.astro

- Fixed menu desktop that don't show links to sections.
- Fixed responsive menu on teams page.

Fixes to menu. 

---

README.en.md
README.md

add replic version of readme in 🇬🇧, link in main readme with url.

feat: english version readme 🇬🇧

---

src/components/Sponsors.astro

Adding a link to each partner's web site in Sponsors section

feat: add links to sponsors web sites

---

src/components/Header.astro

En el menú del navegación queda por detras de la card de los equipos en la ruta team/[teamid]
PD: Mi segundo pr de la vida

Fix z-index in navbar menu mobile

---

src/components/Leaderboard.astro

💅 Add shortName in the responsive

Add shortName in the responsive

---

.gitignore

Exclude dummy files of git

---

scraping/index.js
scraping/leaderboard.js
scraping/mvp.js
scraping/players_twelve.js
scraping/presidents.js
scraping/short_name_teams.js
scraping/teams.js
scraping/top_assists.js
scraping/top_scorers.js
scraping/top_statistics.js
scraping/url_teams.js
scraping/utils.js

Fix some imports that were failing

Fix: fix imports in scrapping scripts

---

README.en.md

una forma de volver al README en español

add missing link to README.md

---

src/components/ScheduleRow.astro

Fix #254. 
<table><tr><td>
<p>Before:</p>
</td><td>
<p>After:</p>
</td></tr></table>
Also fix it lg and md screens.

Fix: Same width for all the "score" cells

---

src/components/Sponsors.astro

I'm fix the size of logos partners on mobile.
Before:
After:
Others changes:
- Add aspect ratio of logos.

sponsors section improvements

---

src/pages/team/[teamId].astro

add filter to turns **tiktok** svg as img `white` in socials teams page `/team/el-barrio`

fix social team tiktok icon

---

src/components/Assistants.astro
src/components/Goals.astro
src/components/Leaderboard.astro
src/components/MVP.astro

- Improved the hover color contrast between even and odd rows

Improve contrast on hover Statistics rows

---

api/index.test.js

Refactor test to use the `checkProperties` function and avoid repeating loops / validations.

Feat: Refactor tests

---

src/components/ScheduleRow.astro

Change background color table team on hover

style: table hover change to gray-200 background

---

.github/workflows/scrape-kings-league-web.yml

added a cron job to scrape dayly the web at 12pm.

Daily Cron Job: 12PM

---

src/components/TeamPagePlayers.astro
src/pages/team/[teamId].astro

FEAT: 💅  Team division by positions

add: team division by positions

---

src/pages/estadisticas/clasificacion/index.astro

fix  the responsive of the players' cards
after
before

FIX: the responsive of the players' cards

---

src/components/Header.astro
src/pages/jugador-12/index.astro
src/services/teams.js

* Add new function getAllPlayersTwelve
* Add new link of player page
* FEAT: 💅  player page 12

Add new player page 12

---

src/components/Sponsors.astro

Added automatic left and right margins on sponsors logos. Prevents asymmetric spacing that can exist between them.
i<3u

Center sponsors logos

---

src/pages/jugador-12/index.astro

FEAT: Add description in the page player twelve

---

db/players_twelve.json
src/components/Header.astro
src/components/SocialNetworks.astro

Issue where the nav and background were breaking on tablet resolutions has been fixed. Specific changes have been applied to ensure the nav and background display correctly on these resolutions.
**Before:**
**After:**

Fix for nav and background issue on tablet resolutions

---

src/components/Leaderboard.astro
src/pages/calendario/index.astro
src/pages/estadisticas/clasificacion/index.astro

feat: mark positions that qualify to playoffs
