midudev/kings-league-project

api/index.test.js
Setup and teardown functions have been created to start and stop the application worker, respectively. These functions are used in the beforeAll and afterAll of each describe.
The { disableExperimentalWarning: true } parameter has been removed when starting the worker.
The assertResponseOk function has been added to verify that the worker's response is correct before processing it.
The check for a null response has been removed before trying to process it. If the response is null, the assertResponseOk function will throw an exception.
The check for the '/teams/1k' route has been removed since the team's ID should be an integer and not a string.
Comments that do not provide relevant information have been removed.
In summary, these changes aim to improve the readability and robustness of …
=> Add: new tests

package.json
This Pull Request adds two new commands, lint and format, to the package.json file. These commands can be used to enforce code styling in the project. The lint command checks for syntax and style issues, and the format command automatically formats the code to conform to the project's style guide. This ensures that all code in the project is consistently formatted and easy to read.
=> Add Lint and Format Commands

api/index.js
- Change `top_scorer` identifier to use camel case notation as is used in standard eslint
- Typos `coachs` to `coaches` in `api/index.js` file
=> fix: using camel case notation in identifier to avoid eslint errors

api/index.test.js
Observations:
At this point the tests will fail, for the following:
=> fix: setup worker correctly

.prettierrc.cjs
Hi team,
I've added several new configuration options to the .prettierrc.cjs file to give us more control over how Prettier formats our code.
- The `JsxBracketSameLine` option allows us to specify whether the closing bracket in JSX elements should be on the same line as the opening bracket or on a new line. This can help us maintain a consistent style across our codebase.
- The `htmlWhitespaceSensitivity` option lets us control how Prettier handles whitespace in HTML files. We can choose to preserve the whitespace as it appears in the source code, trim leading and trailing whitespace and collapse multiple spaces, or ignore leading and trailing whitespace and collapse multiple spaces.
- The `arrowParens` option allows us to include parentheses around the arguments of an arrow function when …
=> Add additional configuration options to .prettierrc.cjs file

.eslintrc.cjs, package.json
**Description**
This PR:
- installs and uses [standard eslint plugin](https://github.com/standard/eslint-config-standard)
- installs typescript parser for .astro files. (Cannot get around this because Astro uses typescript by default)
- fixes and removes unused-vars eslint rule
- move eslint config to `.eslintrc.cjs` file
=> fix: eslint use astro parser

CONTRIBUTING.md
Added the Git commit conduct guidelines to the contributing guidelines document.
Updated the Reporting Bugs section in the contributing guidelines to include information about how to properly report a bug.
Fix typeof space and "#to do" show in document user contributing
=> fix: typeof  feat: Add more guidelines in contributing md

db/teams.json, scraping/index.js, scraping/url_teams.js
Es un método que utiliza un patrón de la url de la información de cada equipo de la pagina oficial.
Explicacion de patron de la url:
Las url de la información de cada equipo tiene siempre el patrón de la url base 'https://kingsleague.pro/team/'
añadiéndole el id del equipo.
Ahí lo añado a que se ejecute luego de que haga el scraping de las paginas ya que este como tal no scrapea sino que lo genera automáticamente en local.
=> add method for get url of each team

scraping/top_scorer.js
Delete the `rank` key to keep only `ranking` on top_scorer scrapper, fixing the issues https://github.com/midudev/kings-league-project/issues/61
=> fix: delete rank key on top_scorer scrapper

.npmrc
Added the `.npmrc` file with the `save-exact=true` option, to force the installation of the exact version of each new package that is installed, without the `-E` flag of PNPM
=> add .npmrc file

api/index.js
It seems that the description was copypasted from the top-scorers endpoint.
=> fix: mvp endpoint description

api/index.js
Añade la información de las posibles rutas con parámetros como `/teams` y `/presidents` con el parámetro `:id`
=> add info of parameters in routes that use this

api/index.js
Añado la información de las nuevas rutas añadidas y una descripción a cada ruta que tenga algún parámetro.
`New routes:`
GET `top-scorers/:rank` 
GET `top-assists/:rank` 
Estas y el resto de rutas con parámetros se les añadió una pequeña descripción.
=> fix: add info at new routes and description at all routes with params 

src/components/TeamsSelectorCards.astro, src/pages/team/[teamId].astro
Add `object-contain` class to avoid stretching images on `TeamsSelectorCards` component.
Before:
After: 
Add `object-contain` class to avoid stretching images on `team/[teamId]` page.
Before: 
After:
=> Prevent images to stretch

src/layouts/Layout.astro, src/pages/team/[teamId].astro
Uh oh, looks like we've got a little rebel on our hands! 'channel' here decided to go rogue and cause some trouble, but we were able to tame it and put it back in its place. All's well that ends well, right?
🍻
=> fix: warning -  'channel' is assigned a value but never used

CONTRIBUTING.md
"Recommended" can be an adjective, and you should normally use it instead of "recommendable".
"Recommendable" means that something CAN be recommended, but does not say that it HAS been.
You mostly see "recommendable" on negative statements ("that is not recommendable").
=> fix recommandable to recommended on CONTRIBUTING

src/pages/index.astro
Make home page responsive.
Some after/before screenshots below:
Before in 920px:
After in 920px:
Before in 1200px:
After in 1200px:
In full screen (1920x1080) it remains the same:
Before in full screen:
After in full screen:
=> feat: home page responsive

src/components/Header.astro
Added white social media icons centered to header. Omitting the twitch button so that you can add the button that you have commented whenever you want.
I have duplicated the "SOCIAL_NETWORKS" array, in order to give you the option of doing the refactor.
So that you extract them to the file that you think is convenient.
=> Feat: add kl social media to header

scraping/index.js
Al momento de utilizar el scrape, si no se le envia un parametro, da un error, ya que tomaba la ruta como parametro (scraping/index.js). Para resolverlo, el parametro que se envia debe existir en las key de SCRAPINGS para poder ser scrapeado, si no existe o no se envia el parametro, se hace el scrape completo.
=> Fix scrape parameter

astro.config.mjs, package.json, public/robots.txt, src/layouts/Layout.astro
- Created `robots.txt` file. The option `Sitemap` include the name generated by the [@astrojs/sitemap](https://docs.astro.build/es/guides/integrations-guide/sitemap/) integration (See: [https://docs.astro.build/es/guides/integrations-guide/sitemap/#example-of-generated-files-for-a-two-page-website](https://docs.astro.build/es/guides/integrations-guide/sitemap/#example-of-generated-files-for-a-two-page-website))
- Add  [@astrojs/sitemap](https://docs.astro.build/es/guides/integrations-guide/sitemap/) to generate a `sitemap-index.xml` on every build.
- Added a canonical url generation for every path on src/layouts/Layout.astro.
=> add basic SEO optimizations

astro.config.mjs, package.json
I have installed the [astro-critters](https://github.com/astro-community/astro-critters) integration, which use [Critters](https://github.com/GoogleChromeLabs/critters) under the hood to extract the Critical CSS and lazy load the rest on every path of the project. This improve the First Contentful Paint metric.
=> extract critical css

src/components/TeamPagePlayers.astro
Las fotos de los jugadores se cortan en el vacio y me parece mejor cortarla visualmente con algo.
=> chore: modify player name and position

api/index.test.js, db/index.test.js
I add 2 new test for leaderboard route 🧪
1. Should return a reasonable number of teams for a large number of teams: This test adds a large number of teams to the database, then sends a request to the /leaderboard route and verifies that the server returns a reasonable number of teams (e.g., less than or equal to 100). This test is useful for ensuring that the /leaderboard route performs well with a large number of teams.
2. Teams should be ordered by rank, with tiebreakers applied: This test sends a request to the /leaderboard route and verifies that the returned teams are ordered by their rank in the leaderboard, with tiebreakers applied for teams with the same rank. The tiebreakers could include wins, goals scored, and other criteria. This test is useful for ensuring that the …
=> 🧪Add: new tests for leaderboard route

api/index.test.js, db/index.test.js
1. Should return a 405 status code for invalid request method: This test sends a POST request to the /schedule route, and verifies that the server returns a 405 Method Not Allowed status code. This test is useful for ensuring that the server handles invalid request methods correctly.
2. Should return a 400 status code for missing or invalid query parameters: This test sends a request to the /schedule route with an invalid query parameter, and verifies that the server returns a 400 Bad Request status code. This test is useful for ensuring that the server handles missing or invalid query parameters correctly.
3. Should return an empty array when there are no matches scheduled: This test deletes all the matches from the database, then sends a request to the /schedule route and verifies that …
=> 🧪 Add: new 4 tests for schedule routes 

.gitignore, db/index.test.js
This test isn't passed because of an error in the expected URL
In this PR the URL is corrected and the folder of webstorm configuration is ignored
=> Fix expected url in db/index.test.js

api/index.test.js, db/index.test.js
I add 1 new test for president  route 🧪
- This test sends a request to the /presidents route with the query parameter "team" set to "1k". It then expects the response to be defined and for the returned JSON to contain an array of presidents. It further expects that array to contain at least one president object that has a "teamId" property with a value of "1k". This test is likely checking that the /presidents route is able to filter the returned presidents by team using the "team" query parameter.
Cheers 🍻
=> 🧪 Add: new test for president route

src/components/TeamPagePlayers.astro, src/components/TeamStats.astro, src/pages/team/[teamId].astro
In this pull request I am aiming to fix some styling issues related with how the team interface looks on mobile, I changed the "posición" title to 1.5 because before this the content was overflowing.
Note that the player grid was also modified so the player grid fits on the screen.
=> fix: team styling

.github/workflows/scrape-kings-league-web.yml
When scraped and we don't have a change, we get an error from GIT when we try to commit. Now we don't have any errors when trying to commit. We check first if we have any changes, and after we add and commit. 
Before (without changes in db): 
After(without changes in db):
=> fix: scrapper action when don't have db changes

src/components/ScheduleRow.astro, src/pages/calendario/index.astro
Fix #188. 
Chances on `/calendario` page (Device: iPhone 12/13 mini):
<table><tr><td>
<p>Before:</p>
</td><td>
<p>After:</p>
</td></tr></table>
Chances on `/` page (Device: iPhone 12/13 mini):
<table><tr><td>
<p>Before:</p>
</td><td>
<p>After:</p>
</td></tr></table>
=> Fix: Schedule row / responsive.

api/index.js
>This PR doesn't involve any change on the logic of the API.
- Updated descriptions to be more informative and accurate.
- Add missing  `/teams/:id/players-12` and `/top-statistics`  endpoints.
- Fixed error in endpoint `/top-assists/:teamId`, as it's actually intended to be `/coaches/:teamId`.
=> fix: update api endpoints information

README.en.md, README.md
Hi! I'm proposing to remove the PWA badge from the readme files, since it's not planned to add PWA functionalities, I guess it's not necessary to display them.
=> remove pwa bagde from readme files

src/components/ScheduleRow.astro
I've added a simple hover style in teams name table
To make it a little clear that it is clickable.
=> style: table teams name add a hover gray color

src/pages/estadisticas/clasificacion/index.astro
Buenos dias,
Se ha modificado el css de el contenedor de la imágenes para que en pantallas a partir de escritorio y, si hay mvp, tenga más margin top con el menú de navegación.
El resultado es este:
Issue #292.
Un saludo, muchas gracias
=> Se arregla el menu de navegacion de la pagina de estadisticas

src/pages/contacto/index.astro
FIX: link page contact
after
before
=> FIX: link page contact

src/components/ScheduleRow.astro
Change the "shared" styles. The other lines were changed by prettier.
Mobile:
<table><tr><td>
<p>Before:</p>
</td><td>
<p>After:</p>
</td></tr></table>
Desktop:
<table><tr><td>
<p>Before:</p>
</td></tr>
<tr><td>
<p>After:</p>
</td></tr></table>
=> Fix: Text overlow on score cell when penalties

src/layouts/Layout.astro
The **Open Graph** protocol enables any web page to become a rich object in a social graph.
These changes will improve **SEO** and the **URL preview** when sharing the site in social media as Facebook, WhatsApp, etc.
=> feat: add og meta tags to Layout

README.md
Fixing a typo in `Cheerio` name.
Before: `Cherrio`
After: `Cheerio`
=> Fix the misspelling in `Cheerio` name

src/pages/calendario/index.astro
=> add background header in tables matches (/calendario page)

src/pages/jugador-12/index.astro
=> Fix: Remove `/plublic` prefix on twelve players page

README.en.md, README.md, api/index.js
- Add route to search for a player by his id of a certain team.
-- Example : `/teams/pio-fc/players/1`
=> Add new route for teams endpoint

db/schedule.json, scraping/schedule.js
Fix #323.
The schedule page was changed, so, the scraper didn't work as expected. 
Also the hours for the next matches were added: 
Before: 
After:
=> Fix: Update schedule scraper selectors due to page changes

package.json, public/icons/download-icon.svg, src/components/PlayerFifaBadge.astro
I have submitted a pull request that includes a new feature for downloading player card images in SVG format using the html-to-image library. The decision to use SVG format was made to maintain image quality, however, it is also possible to download the images in PNG format (changes on the code), but this may result in a loss of image quality. I apologize for any issues or inconvenience caused by the implementation of this feature. To ensure that the card images would not be cropped when downloaded, I had to take the following steps:
1. placed the card inside a container
2. extracted the url
3. then returned the card back to its original position
By doing this, I was able to download the player card images without any cropping or loss of quality.
This is my first time working with Astro, …
=> Feature: Added download svg for player cards
